[phases.setup]
nixPkgs = ["python311", "opencv", "ffmpeg", "glib", "libGL"]

[phases.install]
cmds = [
  "pip install --upgrade pip",
  "pip install -r requirements.txt",
  "pip install git+https://github.com/justinshenk/fer.git@22.5.1 --no-deps"
]

[start]
cmd = "uvicorn main:app --host 0.0.0.0 --port 8080"
