[phases.setup]
nixPkgs = ["python311", "opencv", "ffmpeg", "glib", "libGL"]

[phases.install]
cmds = [
    "python -m ensurepip --upgrade",
    "python -m pip install --upgrade pip",
    "python -m pip install -r requirements.txt",
    "python -m pip install git+https://github.com/justinshenk/fer.git@22.5.1 --no-deps"
]

[phases.start]
cmd = "uvicorn main:app --host 0.0.0.0 --port 8080"
